### PR TITLE
Update CodeMirror

### PR DESCRIPTION
**Pull request by cqx931**

### CODE REVIEW

**Comment by dhowe** [comment]
* Line numbers are still incorrect on errors when highlighting part of a script (high)
* Can we adjust line-spacing, it is much bigger than before?
* 'Validate' button should be disabled after text is validated _until_ user changes text (low)

**Comment by cqx931** [comment]
Please check.
- Adjusted line height
- Fixed text selection

**Comment by dhowe** [comment]
Does this address the incorrect line numbers on errors with highlighting?

**Comment by dhowe** [comment]
Strange bug where apparently an old script is loaded from the cookie, however on clicking 'validate' it thinks there is no script present. See image:

image

**Comment by dhowe** [comment]
Another issue: changing the highlighting (similar to changing the text) should make the 'validate' button enabled again, and 'execute' should become disabled.

**Comment by dhowe** [comment]
I am merging this in, but there are still issues:

**Pull request closed without merging**
